import type { Metadata } from 'next';
import { NextFontWithVariable } from 'next/dist/compiled/@next/font';
import { Inter, Playfair_Display } from 'next/font/google';

import { DoubleTransitions, Footer, Navbar } from '@/components';

import './globals.css';

const inter: NextFontWithVariable = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} ${playfair.variable}`}>
      <DoubleTransitions />
      <Navbar />
        <div className='mt-20 p-8'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
