import type { Metadata } from 'next';
import { Inter, Playfair_Display, Caveat, JetBrains_Mono } from 'next/font/google';

import { Cursor, Navbar, PageCurtain } from '@/components';
import { PageTransitionProvider } from '@/context';

import '../styles/globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
  style: ['normal', 'italic'],
});

const caveat = Caveat({
  subsets: ['latin'],
  variable: '--font-caveat',
  style: ['normal'],
});

const jetBrains = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html className={`${inter.variable} ${playfair.variable} ${caveat.variable} ${jetBrains.variable}`} lang='en'>
      <body className='relative'>
        <PageTransitionProvider>
          <PageCurtain />
          <Navbar />
          <div>
            {children}
            <Cursor />
          </div>
        </PageTransitionProvider>
      </body>
    </html>
  );
}
