import type { Metadata } from 'next';
import { Inter, Playfair_Display, Caveat } from 'next/font/google';

import { Cursor, Footer, Navbar, PageCurtain } from '@/components';
import { PageTransitionProvider } from '@/context';

import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
  style: ['normal', 'italic'],
});

const caveat = Caveat({
  subsets: ['latin'],
  variable: '--font-caveat',
  style: ['normal'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html className={`${inter.variable} ${playfair.variable} ${caveat.variable}`} lang='en'>
      <body>
        <PageTransitionProvider>
          <PageCurtain />
          <Navbar />
          <div className='px-8 py-8 md:px-15'>
            {children}
            <Cursor />
          </div>
          {/* <Footer /> */}
        </PageTransitionProvider>
      </body>
    </html>
  );
}
